#!/bin/bash
# NEMS Linux Hardware Detection
# By Robbie Ferguson // The Bald Nerd
# (c) Copyright 2021 Category5 TV Network

cmdline=$(cat /proc/cmdline)

search="${cmdline##*bcm2709.boardrev=}"
boardrev="${search%% *}"

search="${cmdline##*bcm2709.serial=}"
serial="${search%% *}"

if [[ "$boardrev" = *"900021" ]]; then
  model="Raspberry Pi A+"

elif [[ "$boardrev" = *"900032" ]]; then
  model="Raspberry Pi B+"

elif [[ "$boardrev" = *"900092" ]] || [[ "$boardrev" = *"900093" ]] || [[ "$boardrev" = *"920092" ]] || [[ "$boardrev" = *"920093" ]]; then
  model="Raspberry Pi Zero"

elif [[ "$boardrev" = *"9000c1" ]]; then
  model="Raspberry Pi Zero W"

elif [[ "$boardrev" = *"9020e0" ]]; then
  model="Raspberry Pi 3A+"

elif [[ "$boardrev" = *"900061" ]]; then
  model="Raspberry Pi Compute Module"

elif [[ "$boardrev" = *"a01040" ]] || [[ "$boardrev" = *"a01041" ]] || [[ "$boardrev" = *"a02042" ]] || [[ "$boardrev" = *"a21041" ]] || [[ "$boardrev" = *"a22042" ]]; then
  model="Raspberry Pi 2B"

elif [[ "$boardrev" = *"a02082" ]] || [[ "$boardrev" = *"a22082" ]] || [[ "$boardrev" = *"a32082" ]] || [[ "$boardrev" = *"a52082" ]] || [[ "$boardrev" = *"a22083" ]]; then
  model="Raspberry Pi 3B"

elif [[ "$boardrev" = *"a020a0" ]] || [[ "$boardrev" = *"a220a0" ]]; then
  model="Raspberry Pi Compute Module 3"

elif [[ "$boardrev" = *"a020d3" ]]; then
  model="Raspberry Pi 3B+"

elif [[ "$boardrev" = *"a02100" ]]; then
  model="Raspberry Pi Compute Module 3+"

elif [[ "$boardrev" = *"a03111" ]] || [[ "$boardrev" = *"b03111" ]] || [[ "$boardrev" = *"b03112" ]] || [[ "$boardrev" = *"b03114" ]] || [[ "$boardrev" = *"c03111" ]] || [[ "$boardrev" = *"c03112" ]] || [[ "$boardrev" = *"c03114" ]] || [[ "$boardrev" = *"d03114" ]]; then
  model="Raspberry Pi 4B"

elif [[ "$boardrev" = *"c03130" ]]; then
  model="Raspberry Pi 400"

fi

ram=$(free | awk '/^Mem:/{print $2}')

echo $model
echo $ram
